/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";

// Create Virtual Routes

const SessionsLazyImport = createFileRoute("/sessions")();
const OpensourceLazyImport = createFileRoute("/opensource")();
const FeedbackLazyImport = createFileRoute("/feedback")();
const AboutusLazyImport = createFileRoute("/aboutus")();
const IndexLazyImport = createFileRoute("/")();

// Create/Update Routes

const SessionsLazyRoute = SessionsLazyImport.update({
  id: "/sessions",
  path: "/sessions",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/sessions.lazy").then((d) => d.Route));

const OpensourceLazyRoute = OpensourceLazyImport.update({
  id: "/opensource",
  path: "/opensource",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/opensource.lazy").then((d) => d.Route));

const FeedbackLazyRoute = FeedbackLazyImport.update({
  id: "/feedback",
  path: "/feedback",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/feedback.lazy").then((d) => d.Route));

const AboutusLazyRoute = AboutusLazyImport.update({
  id: "/aboutus",
  path: "/aboutus",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/aboutus.lazy").then((d) => d.Route));

const IndexLazyRoute = IndexLazyImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/index.lazy").then((d) => d.Route));

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/aboutus": {
      id: "/aboutus";
      path: "/aboutus";
      fullPath: "/aboutus";
      preLoaderRoute: typeof AboutusLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/feedback": {
      id: "/feedback";
      path: "/feedback";
      fullPath: "/feedback";
      preLoaderRoute: typeof FeedbackLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/opensource": {
      id: "/opensource";
      path: "/opensource";
      fullPath: "/opensource";
      preLoaderRoute: typeof OpensourceLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/sessions": {
      id: "/sessions";
      path: "/sessions";
      fullPath: "/sessions";
      preLoaderRoute: typeof SessionsLazyImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexLazyRoute;
  "/aboutus": typeof AboutusLazyRoute;
  "/feedback": typeof FeedbackLazyRoute;
  "/opensource": typeof OpensourceLazyRoute;
  "/sessions": typeof SessionsLazyRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexLazyRoute;
  "/aboutus": typeof AboutusLazyRoute;
  "/feedback": typeof FeedbackLazyRoute;
  "/opensource": typeof OpensourceLazyRoute;
  "/sessions": typeof SessionsLazyRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexLazyRoute;
  "/aboutus": typeof AboutusLazyRoute;
  "/feedback": typeof FeedbackLazyRoute;
  "/opensource": typeof OpensourceLazyRoute;
  "/sessions": typeof SessionsLazyRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/aboutus" | "/feedback" | "/opensource" | "/sessions";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/aboutus" | "/feedback" | "/opensource" | "/sessions";
  id: "__root__" | "/" | "/aboutus" | "/feedback" | "/opensource" | "/sessions";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute;
  AboutusLazyRoute: typeof AboutusLazyRoute;
  FeedbackLazyRoute: typeof FeedbackLazyRoute;
  OpensourceLazyRoute: typeof OpensourceLazyRoute;
  SessionsLazyRoute: typeof SessionsLazyRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutusLazyRoute: AboutusLazyRoute,
  FeedbackLazyRoute: FeedbackLazyRoute,
  OpensourceLazyRoute: OpensourceLazyRoute,
  SessionsLazyRoute: SessionsLazyRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/aboutus",
        "/feedback",
        "/opensource",
        "/sessions"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/aboutus": {
      "filePath": "aboutus.lazy.tsx"
    },
    "/feedback": {
      "filePath": "feedback.lazy.tsx"
    },
    "/opensource": {
      "filePath": "opensource.lazy.tsx"
    },
    "/sessions": {
      "filePath": "sessions.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
