name: Build and Deploy

on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: [self-hosted,hetzner]

    steps:
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/checkout@v2

      - name: Copy .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Run react build script
        run: pnpm install && pnpm build
